[package]
name = "cita_recover"
version = "0.1.0"
authors = ["yubo <yubo@cryptape.com>"]

[dependencies]
clap = "2.32.0"
log = "0.4.6"
cita-types = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
common-types = { path = "./types" }
proof = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
db = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
rlp = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
libproto = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }